### ISSUE TITLE
[TODO]: Implement prune branches

### ISSUE THREAD

**Issue by DJBlackEagle** [DJBlackEagle/simple-git-tools#89]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues
- [X] I use the right issue type

### Describe your todo.

Steps:

- [x] Add commander (NPM)
- [x] Add simple-git (NPM)
- [x] Add colors (NPM)
- [x] Implement the command pruneGoneBranches
- [x] Add a cli file
